name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test backend
      run: |
        cd backend/account
        npm install
        npx jest
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Run Docker Compose
      run: docker-compose up -d
    
    - name: Run tests in Docker
      run: |
        docker-compose exec backend npm test
        docker-compose exec frontend npm test 